services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postcard_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postcard_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postcard_db"]
      interval: 5s
      timeout: 5s
      retries: 5