version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postcard_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postcard_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  postcard_service:
    build: ./postcard_service
    ports:
      - "5001:5000"
    depends_on:
      - db

volumes:  # Этот раздел должен быть в корне файла
  db_data:  # Объявляем том