services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postcard_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postcard_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postcard_service:
    build: ./postcard_service
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy

  user_service:
    build: ./user_service
    ports:
      - "5002:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: