version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postcard_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postcard_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postcard_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  postcard_service:
    build: ./postcard_service
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/postcard_db"
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
    volumes:
      - ./postcard_service:/app
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: